spring:
  profiles:
    include:
      - local

  sql:
    init:
      schema-locations: classpath:sql/oauth2-client-schema.sql
      encoding: UTF-8
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            scope: name, email
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          kakao:
            client-name: kakao
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            scope: profile_nickname, account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  issuer: Petsitter
  client-secret: K7na2VryLl+P8fWTG9vReR3F2pztYwLk8nSKTrs05zU=
  expiry-seconds: 3600